### ISSUE TITLE
AssertionError: "undefined" === "function" (mini-files.js:77:10)

### ISSUE THREAD

**Issue by jackboberg** [onmodulus/docker-build-meteor#28]
Many users experiencing this specific issue.

Reference: onmodulus/docker-build-meteor#25

**Comment by nickoj81** [comment]
@jackboberg Is there any work around while this is being looked at?

**Comment by jackboberg** [comment]
Can anyone experiencing this issue share their source?
- link to open source repo
- send a `zip` to help@modulus.io
- add me to your project (temporarily, read-only)

I'd like to run thru some tests and see if I can spot next steps.

**Comment by jackboberg** [comment]
@nickoj81 I have not found any solutions to this specific issue yet..

**Comment by parisk** [comment]
Hello everyone. I am trying to publish a simple Meteor project like the following but I get this error as well: https://github.com/parisk/meteor-example.

Feel free to use the source code as you wish.

**Comment by jackboberg** [comment]
@parisk can you add the `.meteor` directory so I can be sure we are all synchronized?

**Comment by parisk** [comment]
Sure. Just did.

**Comment by jackboberg** [comment]
~~Able to reproduce in dev environment now, exactly what I needed to move forward.~~ Thank you @parisk 

I'll report back as soon as I make some progress...

---

Update: I believe my issue was simply not setting the node version (too quick attempting to start debugging)

`› modulus deploy --node-version 4 # works with this sample code`

**Comment by parisk** [comment]
Awesome, looking forward to it!

**Comment by jackboberg** [comment]
FYI: I have that code running here: http://minifiles-130.dev.mod.ec

`› modulus deploy -p mini-files --node-version 4`

This is targeting out dev environment, testing a simple change to our build where we do not pass `--production` [here](https://github.com/onmodulus/docker-build-meteor/blob/master/bin/build#L94). That doesn't make a lot of sense to me, attempting to verify that was actually a 'fix'...

**Comment by jackboberg** [comment]
OK, it seems that was unrelated (another dev attempting to resolve onmodulus/docker-run-meteor#12)..

I am actually able to deploy this to the public cloud without issue:

create a project

```
› modulus project create
Welcome to Modulus
You are logged in as jack
[?] Enter a project name: mini-files
Please choose which runtime to use:
  1) Node.js
  2) Java
  3) Static
  4) Python (beta)
  5) DNX (beta)
  6) Meteor (beta)
[?] Image number? 6
[?] Enter a servo size in MB [192, 396, 512, 1024, or 2048] (optional, default 512): 396
Please choose the owner for this project:
  1) jack
  2) ...
[?] Organization number? 1
Assigning project owner: jack
[✓] New project mini-files created.
```

set env var

```
› modulus env set ROOT_URL http://minifiles-88047.onmodulus.net -p mini-test
```

deploy

```
› modulus deploy -p mini-files --node-version 4
Welcome to Modulus
You are logged in as jack
Selecting mini-files

Deploying Meteor version 1.4.0.1

Compressing project...
4.1 KB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v4.4.7 (npm v3.10.5)
Initializing Meteor environment.
Using METEOR@1.4.0.1.
Node version 4 specified.
Demeteorizing application...
Demeteorization complete.
deploy -> v4.5.0
Installing root package.json dependencies.
project@ /mnt/input
└─┬ meteor-node-stubs@0.2.3
  ├── assert@1.3.0
  ├─┬ browserify-zlib@0.1.4
  │ └── pako@0.2.8
  ├─┬ buffer@4.5.1
  │ ├── base64-js@1.1.2
  │ ├── ieee754@1.1.6
  │ └── isarray@1.0.0
  ├─┬ console-browserify@1.1.0
  │ └── date-now@0.1.4
  ├── constants-browserify@1.0.0
  ├─┬ crypto-browserify@3.11.0
  │ ├─┬ browserify-cipher@1.0.0
  │ │ ├─┬ browserify-aes@1.0.6
  │ │ │ ├── buffer-xor@1.0.3
  │ │ │ └── cipher-base@1.0.2
  │ │ ├─┬ browserify-des@1.0.0
  │ │ │ ├── cipher-base@1.0.2
  │ │ │ └─┬ des.js@1.0.0
  │ │ │   └── minimalistic-assert@1.0.0
  │ │ └── evp_bytestokey@1.0.0
  │ ├─┬ browserify-sign@4.0.0
  │ │ ├── bn.js@4.11.1
  │ │ ├── browserify-rsa@4.0.1
  │ │ ├─┬ elliptic@6.2.3
  │ │ │ ├── brorand@1.0.5
  │ │ │ └── hash.js@1.0.3
  │ │ └─┬ parse-asn1@5.0.0
  │ │   ├─┬ asn1.js@4.5.2
  │ │   │ └── minimalistic-assert@1.0.0
  │ │   ├─┬ browserify-aes@1.0.6
  │ │   │ ├── buffer-xor@1.0.3
  │ │   │ └── cipher-base@1.0.2
  │ │   └── evp_bytestokey@1.0.0
  │ ├─┬ create-ecdh@4.0.0
  │ │ ├── bn.js@4.11.1
  │ │ └─┬ elliptic@6.2.3
  │ │   ├── brorand@1.0.5
  │ │   └── hash.js@1.0.3
  │ ├─┬ create-hash@1.1.2
  │ │ ├── cipher-base@1.0.2
  │ │ ├── ripemd160@1.0.1
  │ │ └── sha.js@2.4.5
  │ ├── create-hmac@1.1.4
  │ ├─┬ diffie-hellman@5.0.2
  │ │ ├── bn.js@4.11.1
  │ │ └─┬ miller-rabin@4.0.0
  │ │   └── brorand@1.0.5
  │ ├── inherits@2.0.1
  │ ├── pbkdf2@3.0.4
  │ ├─┬ public-encrypt@4.0.0
  │ │ ├── bn.js@4.11.1
  │ │ ├── browserify-rsa@4.0.1
  │ │ └─┬ parse-asn1@5.0.0
  │ │   ├─┬ asn1.js@4.5.2
  │ │   │ └── minimalistic-assert@1.0.0
  │ │   ├─┬ browserify-aes@1.0.6
  │ │   │ ├── buffer-xor@1.0.3
  │ │   │ └── cipher-base@1.0.2
  │ │   └── evp_bytestokey@1.0.0
  │ └── randombytes@2.0.3
  ├── domain-browser@1.1.7
  ├── events@1.1.0
  ├─┬ http-browserify@1.7.0
  │ ├── Base64@0.2.1
  │ └── inherits@2.0.1
  ├── https-browserify@0.0.1
  ├── os-browserify@0.2.1
  ├── path-browserify@0.0.0
  ├── process@0.11.2
  ├── punycode@1.4.1
  ├── querystring-es3@0.2.1
  ├─┬ readable-stream@2.0.6
  │ ├── core-util-is@1.0.2
  │ ├── inherits@2.0.1
  │ ├── isarray@1.0.0
  │ ├── process-nextick-args@1.0.6
  │ └── util-deprecate@1.0.2
  ├─┬ stream-browserify@2.0.1
  │ └── inherits@2.0.1
  ├── string_decoder@0.10.31
  ├── timers-browserify@1.4.2
  ├── tty-browserify@0.0.0
  ├─┬ url@0.11.0
  │ ├── punycode@1.3.2
  │ └── querystring@0.2.0
  ├─┬ util@0.10.3
  │ └── inherits@2.0.1
  └─┬ vm-browserify@0.0.4
    └── indexof@0.0.1

Installing packages from /mnt/output/bundle/programs/server/package.json
WARN: npm-shrinkwrap.json will override dependencies declared in package.json.

> fibers@1.0.13 install /mnt/output/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-4.5` exists; testing
Binary is fine; exiting
meteor-dev-bundle@0.0.0 /mnt/output/bundle/programs/server
├── amdefine@1.0.0
├── ansi-regex@0.2.1
├── ansi-styles@1.1.0
├── asap@2.0.4
├── escape-string-regexp@1.0.5
├── fibers@1.0.13
├── has-ansi@0.1.0
├── meteor-promise@0.7.2
├── promise@7.1.1
├── semver@4.1.0
├── source-map@0.1.32
├── source-map-support@0.3.2
├── strip-ansi@0.3.0
├── supports-color@0.2.0
├── type-of@2.0.1
└── underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
Uploading completed build.
Provisioning and deploying bundle to servos...

[✓] mini-files running at minifiles-88047.onmodulus.net
```

http://minifiles-88047.onmodulus.net

**Comment by talfco** [comment]
ok i did some research and found the following  issue https://github.com/meteor/meteor/issues/7475 which is talking about a similar problem. Somewhere  it mentions that **node v4.x.x** is mandatory.

When I run the deploy I get

Compressing project...
1.2 MB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
**Now using node v4.4.7 (npm v3.10.5)**
Initializing Meteor environment.
Using METEOR@1.4.0.1.
Demeteorizing application...
Demeteorization complete.
**deploy -> v0.10.41**
Installing root package.json dependencies.
npm WARN cloudburoCurationPlatform@1.0.0 No repository field.
npm WARN cloudburoCurationPlatform@1.0.0 No license field.

In the deploy stage it mentions v0.10.41 for node, in @jackboberg  sample abov the deploy statement in the log is v4.5.0. 

So how can I change the deploy from v0.10.41 to v4.5.0 could potentially fix the problem?

**Comment by jackboberg** [comment]
@talfco try updated CLI and instructions [here](https://github.com/onmodulus/docker-build-meteor/issues/25#issuecomment-240119384)

**Comment by talfco** [comment]
updating CLI and followed instructions  fixed for me this issue (mini-file.js)! I still have some problems within my server code (functional problems of my code with a slack module), but the meteor startup sequence is now working.

**Comment by talfco** [comment]
just one additional note to my last comment. So the server is starting up but my startup sequence fails:

```
info: OAuth.slackApp.registerService called
/mnt/app/bundle/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                        ^
Error: Cannot find module 'slackbots'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.Npm.require (/mnt/app/bundle/programs/server/boot.js:171:18)
    at server/slack/slackStartup.coffee:6:26
    at /mnt/app/bundle/programs/server/boot.js:304:5
```

Seems like my NPM.require statement will not get included in the package.json on the server

```
Meteor.startup () ->
  exports.SlackBot = Npm.require('slackbots')
  authUrl = 'https://slack.com/api/rtm.start'
```

Update:
I did a reinstall of the npm module to be 100% sure but failure stays

```
meteor npm install slackbots
cloudburoCurationPlatform@1.0.0 /Users/felix/Development/meteor/clb-memberzone
└── slackbots@0.5.2 
```

There is an issue https://github.com/thereactivestack/kickstart-meteor-react-router/issues/64 which discuss that in context of Modulus and is closed. Is that related here or should I open another issue ?

**Comment by nickoj81** [comment]
Updating the cli and deploying as suggested [here](https://github.com/onmodulus/docker-build-meteor/issues/25#issuecomment-240119384) has not fixed the mini-files.js error for me

This is the log when deploying the app

```
Deploying Meteor version 1.4.0.1

Compressing project...
610.4 KB written
Uploading project...
Upload progress [===================] 100%
Deploying project into Meteor runtime...
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v4.4.7 (npm v3.10.5)
Initializing Meteor environment.
Using METEOR@1.4.0.1.
Node version 4 specified.
Demeteorizing application...
saffron:logging: updating npm dependencies -- winston, winston-logentries...

Unable to resolve some modules:

  "braintree-web" in /mnt/input/client/views/header.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save braintree-web


Unable to resolve some modules:

  "braintree" in /mnt/input/server/apiKeys/braintreeCred.js (os.linux.x86_64)
  "twilio" in /mnt/input/server/apiKeys/twilioCred.js (os.linux.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save braintree twilio

Demeteorization complete.

```

And this is the log from the server with mini-files.js issue

```

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/mnt/app/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/app/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "node" "/mnt/app/.modulus/nvm/v0.10.41/bin/npm" "start"
npm ERR! node v0.10.41
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/bundle/programs/server/npm-debug.log
Now using node v0.10.41 (npm v3.10.6)
Found package.json: ./bundle/programs/server/package.json
Running command: npm start

> meteor-dev-bundle@0.0.0 start /mnt/app/bundle/programs/server
> node ../../main

```

**Comment by jackboberg** [comment]
@talfco Seems like maybe you are seeing onmodulus/docker-run-meteor#12 now, I'd like to keep this issue focused on `mini-files` to avoid confusion.

@nickoj81 Can you share the source?
- link to open source repo
- send a zip to help@modulus.io
- add me to your project (temporarily, read-only)

**Comment by jackboberg** [comment]
@nickoj81 unless you truncated that log, it seems possible you are looking at the error on a previous deploy. Can you confirm by doing a `modulus logs clear` and re-deploying?

**Comment by nickoj81** [comment]
@jackboberg Project repo is on Bitbucket, have sent a zip to help@modulus.io. I have cleared logs and redeployed but the logs are not connecting to the project at the moment, will update.

**Comment by ykptke** [comment]
I created demo meteor app and deploy modulus but I have same problem missing dependencies

**Comment by jackboberg** [comment]
new build image and CLI is public, please update and try deploying again if you were having issues..

`npm i modulus@latest -g`

**Comment by talfco** [comment]
@jackboberg did the update but unfortunately still get a dependency error. But it's another error message as before, asking me about not having called 'Npm.depends'

/usr/local/bin/modulus -> /usr/local/lib/node_modules/modulus/bin/modulus
/usr/local/lib
└── modulus@6.3.0 

``````
info: OAuth.slackApp.registerService called
/mnt/app/bundle/programs/server/node_modules/fibers/future.js:280
                        throw(ex);
                        ^

Error: Can't find npm module 'slackbots'. Did you forget to call 'Npm.depends' in package.js within the 'server' package?
    at Object.Npm.require (/mnt/app/bundle/programs/server/boot.js:203:17)
    at server/slack/slackStartup.coffee:6:26
    at /mnt/app/bundle/programs/server/boot.js:304:5

npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/mnt/app/.modulus/nvm/versions/node/v4.5.0/bin/node" "/mnt/app/.modulus/nvm/versions/node/v4.5.0/bin/npm" "start"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! meteor-dev-bundle@0.0.0 start: `node ../../main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 start script 'node ../../main'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/bundle/programs/server/npm-debug.log
Now using node v4.5.0 (npm v3.10.6)
Found package.json: ./bundle/programs/server/package.json
Running command: npm start ```
``````

**Comment by ykptke** [comment]
Great work. Thanks. :+1:

**Comment by abcd-ca** [comment]
Working for me, good job and thanks!

**Comment by talfco** [comment]
Finally it worked for me as well - thanx.

The last error above I could resolve by installing the failing slackbots package by using the --save option. 

`meteor npm install --save slackbots`

**Comment by nickoj81** [comment]
Seems to be sorted for me now. Thanks

**Comment by theworkflow** [comment]
Closing this issue. If anyone continues to experience this problem, please comment and reopen this issue.
